# Generated by Django 4.1 on 2022-10-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_eventos', '0002_alter_evento_db_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_db',
            name='propietario',
        ),
    ]
